import { FILE_NAME, GLOBAL_FILE_NAME } from "../constants/file-name";
import { FILE_SUBGROUP } from "../constants/file-subgroup";

export const TEMPLATE_DEFAULT: Template = {
  [FILE_SUBGROUP.LEERKRACHTENMATERIAAL]: [
    FILE_NAME.THEMAVOORBEREIDING,
    FILE_NAME.ACHTERGRONDINFORMATIE,
    GLOBAL_FILE_NAME.TIJDSVAKKENOVERZICHT,
    FILE_NAME.MATERIALENLIJST,
  ],
  [FILE_SUBGROUP.LESMATERIAAL]: [
    FILE_NAME.DOEBOEK,
    FILE_NAME.ANTWOORDEN_DOEBOEK,
    FILE_NAME.WERKBLAD,
    FILE_NAME.ANTWOORDEN_WERKBLAD,
  ],
  [FILE_SUBGROUP.EXTRA_LESMATERIAAL]: [
    FILE_NAME.SAMENVATTING,
    FILE_NAME.BELANGRIJKE_WOORDEN,
    GLOBAL_FILE_NAME.VOORTGANGSBLAD,
    FILE_NAME.EXTRA_LESMATERIAAL,
  ],
  [FILE_SUBGROUP.DIFFERENTIATIEMATERIAAL]: [
    FILE_NAME.WERKBLAD,
    FILE_NAME.ANTWOORDEN_WERKBLAD,
    FILE_NAME.DOEBOEK,
    FILE_NAME.ANTWOORDEN_DOEBOEK,
  ],
};
