export const FILE_NAME = {
  THEMAVOORBEREIDING: "Themavoorbereiding",
  ACHTERGRONDINFORMATIE: "Achtergrondinformatie",
  MATERIALENLIJST: "Materialenlijst",
  DOEBOEK: "Doeboek",
  ANTWOORDEN_DOEBOEK: "Antwoorden doeboek",
  SAMENVATTING: "Samenvatting",
  BELANGRIJKE_WOORDEN: "Belangrijke woorden",
  WERKBLAD: "Werkblad",
  WERKBLAD_PLUS: "Werkblad plus",
  ANTWOORDEN_WERKBLAD: "Antwoorden werkblad",
  WERKBLADEN_EXTRA_BEGELEIDING: "Werkbladen extra begeleiding",
  WERKBLADEN_EXTRA_UITDAGING: "Werkbladen extra uitdaging",
  OEFENBLAD: "Oefenblad",
  TOETS_KENNIS: "Toets kennis",
  ANTWOORDEN_TOETS_KENNIS: "Antwoorden toets kennis",
  TOETS_TOEPASSING: "Toets toepassing",
  ANTWOORDEN_TOETS_TOEPASSING: "Antwoorden toets toepassing",
  EXTRA_LESMATERIAAL: "Extra lesmateriaal",
  HANDLEIDING_DOEBOEK: "Handleiding doeboek",
  ALGEMENE_HANDLEIDING: "Algemene handleiding",
  ZELF_ONDERZOEKEN_JUNIOR: "Zelf onderzoeken Junior",
  //   BEKIJK_DE_ACTIVITEITENCATALOGUS: "Bekijk de activiteitencatalogus",
  //   UITLEGVIDEO_1: "Uitlegvideo 1",
  //   UITLEGVIDEO_2: "Uitlegvideo 2",
  TEXT_A: "Tekst A",
  TEXT_B: "Tekst B",
  BOEKENLIJST: "Boekenlijst",
  TEKST_ZELF_ONDERZOEKEN: "Tekst zelf onderzoeken",
  BEOORDELINGSFORMULIER: "Beoordelingsformulier",
  TEKSTEN: "Teksten",
  WERKBLADEN: "Werkbladen",
  ANTWOORDEN_WERKBLADEN: "Antwoorden werkbladen",
  WOORDENSCHAT_TEGEL: "Woordenschat-tegel",
  DISCUSSIEBLAD: "Discussieblad",
  ANTWOORDEN_DISCUSSIEBLAD: "Antwoorden discussieblad",
  LEERWERKSCHRIFT: "Leerwerkschrift", // used for Dutch language, overwrites 'Doeboek'
  ANTWOORDEN_LEERWERKSCHRIFT: "Antwoorden leerwerkschrift", // used for Dutch language, overwrites 'Antwoorden doeboek'
  BELANGRIJKE_WOORDEN_TEGEL: "Belangrijke woorden-tegel",
  MEER_LEZEN_TEGEL: "Meer lezen?-tegel",
  VERDER_OEFENEN_TEGEL: "Verder oefenen-tegel",
} as const;

// Global files
export const GLOBAL_FILE_NAME = {
  TENTOONSTELLING: "Tentoonstelling",
  VOORSTELLING: "Voorstelling",
  POSTER: "Poster",
  ONTWERP: "Ontwerp",
  MUURKRANT: "Muurkrant",
  DEMONSTRATIE: "Demonstratie",
  NIEUWSBERICHT: "Nieuwsbericht",
  LAPBOOK: "Lapbook",
  WERKSTUK: "Werkstuk",
  PRESENTATIE: "Presentatie",
  STAPPENPLAN: "Stappenplan",
  HULPBLAD_ONDERZOEKSVRAAG: "Hulpblad onderzoeksvraag",
  PROJECTBOEK: "Projectboek",
  VOORTGANGSBLAD: "Voortgangsblad",
  EVALUATIEBLAD: "Evaluatieblad",
  TOETSNORMERING: "Toetsnormering",
  TIJDSVAKKENOVERZICHT: "Tijdsvakkenoverzicht",
  KIESKAARTEN: "Kieskaarten",
  MINDMAP: "Mindmap",
  LEGE_WOORDENPOSTERS: "Lege woordenposters",
  TOETS_ANALYSEBLAD: "Toets analyseblad",
  BOEKBESPREKING: "Boekbespreking",
  NIEUWSPRESENTATIE: "Nieuwspresentatie",
  ONDERSTEUNINGSTIPS_PER_LEESDOMEIN: "Ondersteuningstips per leesdomein",
};
